apiVersion: v1
kind: Service
metadata:
  name: dolph-service
spec:
  type: LoadBalancer
  selector:
    app: dolph-app
  ports:
    - protocol: TCP
      port: 5432        # The port PostgreSQL listens on
      targetPort: 5432  # The container's port for PostgreSQL

